### ISSUE TITLE
Suggested changes to project structure

### ISSUE THREAD

**Issue by sirockin** [quii/go-specs-greet#5]
While working through the non-guided parts of the tutorial at the end, I realised I still had some trouble reasoning about some of the relationships between domain code, drivers, adapters, unit tests, specs etc, which may be helped by the following:

- Put the domain code and unit tests (currently in project root) into a `domain` subfolder and package
- Rename the `Driver` types and files to `TestDriver` to make it clear that they are only used for testing (I don't think it's possible to put these in `driver_test.go` files or `*_test` packages since it [wouldn't then be possible to import them](https://github.com/golang/go/issues/39565)
- Move the `GreetAdapter`/`CurseAdapter` types into `greet_test.go`/`curse_test.go` since they are only used for testing and are only used within that file
- use of import aliases was slightly confusing. This is partially but not completely fixed by moving domain code to its own folder.
    - `go_specs_greet` is used in some code to import the root package and in other code to import `./adapters/httpserver`
    - `gospecsgreet` is also used by some code to import the root package

Thanks again for a very useful and thought-provoking chapter.

**Comment by sirockin** [comment]
[This PR](https://github.com/quii/go-specs-greet/pull/7/files) demonstrates the changes I'm proposing but does not yet update `README.md` 

If you think any of these suggestions are useful, I'll be happy to make any necessary adjustments and update `README.md`.

**Comment by quii** [comment]
> Put the domain code and unit tests (currently in project root) into a domain subfolder and package

I think for this example it's not necessary. Granted, some people might _arrive_ at that structure, but that's fine. I hate to have tutorials that mandate very explicit structures without clear motivation. I'd rather teach people to figure out structures for themselves. In this example, I don't think a domain folder helps too much

> Rename the Driver types and files to TestDriver to make it clear that they are only used for testing (I don't think it's possible to put these in driver_test.go files or *_test packages since it https://github.com/golang/go/issues/39565

Do we _have_ to constrain `Drivers` to be only used in tests? They don't take any specific test dependencies. I have a real life example where we effectively re-use these things in little command-line utility apps. Another way of looking at drivers is that they are clients to our app. 

> Move the GreetAdapter/CurseAdapter types into greet_test.go/curse_test.go since they are only used for testing and are only used within that file 

Not sure. It's the domain code wanting to adapt itself, rather than the specification trying to adapt the domain code. I prefer it as is. 

> use of import aliases was slightly confusing. This is partially but not completely fixed by moving domain code to its own folder.

Agreed, this isn't great

**Comment by quii** [comment]
To be fair to you, although I disagree with `domain` (as it's far too wooly in itself), I could be convinced if we could come up with a collective noun for what greet and curse are. That would improve the imports, which would improve the readability, rather than the weird `go_specs_greet.Greet` stuff we have right now. `interaction` ?

**Comment by quii** [comment]
```go
package grpcserver

import (
	"context"

	"github.com/quii/go-specs-greet/domain/interact"
)

type GreetServer struct {
	UnimplementedGreeterServer
}

func (g GreetServer) Curse(ctx context.Context, request *CurseRequest) (*CurseReply, error) {
	return &CurseReply{Message: interact.Curse(request.Name)}, nil
}

func (g GreetServer) Greet(ctx context.Context, request *GreetRequest) (*GreetReply, error) {
	return &GreetReply{Message: interact.Greet(request.Name)}, nil
}
```

This feels better I think?

**Comment by sirockin** [comment]
> This feels better I think?

Yes definitely.

**Comment by sirockin** [comment]
> Do we _have_ to constrain `Drivers` to be only used in tests? They don't take any specific test dependencies. I have a real life example where we effectively re-use these things in little command-line utility apps. Another way of looking at drivers is that they are clients to our app.

I guess not but if they're not required elsewhere *right now* wouldn't encapsulation and YAGNI suggest we should keep their scope tight? For me though it was more a question of finding my way around the project structure (with my admittedly COVID-addled brain :-) )

**Comment by sirockin** [comment]
> Not sure. It's the domain code wanting to adapt itself, rather than the specification trying to adapt the domain code. I prefer it as is.

I'm not sure if I understand the point. it looks to me as if the Curse/GreetAdapters are purely there to provide because the *tests* want to provide bridge from the domain to the specs. I guess it depends on which way you look at it :-)

My motivations for putting it there were:
- Keep the domain code clean
- Make it easier to reason about how the tests use the adapter (I have a few years' experience writing go but I still find functions with receivers slightly non-intuitive)

Anyway, these are only suggestions, thanks for responding and discussing.

**Comment by quii** [comment]
Just pushed the domain changes, now have to dash!

**Comment by sirockin** [comment]
Great, thanks again for producing this and responding to my suggestions.
